// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GZmKqk2zpCibMxPBTBPKXXPkTboWOCA',
    appId: '1:775284469031:web:e915b1b2b30869a89a8d02',
    messagingSenderId: '775284469031',
    projectId: 'lotaya-3d',
    authDomain: 'lotaya-3d.firebaseapp.com',
    storageBucket: 'lotaya-3d.appspot.com',
    measurementId: 'G-WKY4XRRWBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxlLbwfuQQ2Pa9yB2v90YilGQeEieflI',
    appId: '1:775284469031:android:9e8879458d3585429a8d02',
    messagingSenderId: '775284469031',
    projectId: 'lotaya-3d',
    storageBucket: 'lotaya-3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjmnvseTSEqcTcXoDKpNWWkThUzfHv-s',
    appId: '1:775284469031:ios:1ecded070c4eefc09a8d02',
    messagingSenderId: '775284469031',
    projectId: 'lotaya-3d',
    storageBucket: 'lotaya-3d.appspot.com',
    iosBundleId: 'com.digit.lotaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgjmnvseTSEqcTcXoDKpNWWkThUzfHv-s',
    appId: '1:775284469031:ios:1ecded070c4eefc09a8d02',
    messagingSenderId: '775284469031',
    projectId: 'lotaya-3d',
    storageBucket: 'lotaya-3d.appspot.com',
    iosBundleId: 'com.digit.lotaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0GZmKqk2zpCibMxPBTBPKXXPkTboWOCA',
    appId: '1:775284469031:web:1452c7146c2684829a8d02',
    messagingSenderId: '775284469031',
    projectId: 'lotaya-3d',
    authDomain: 'lotaya-3d.firebaseapp.com',
    storageBucket: 'lotaya-3d.appspot.com',
    measurementId: 'G-T06Y42R480',
  );

}