// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4-nnN59UBU47tFkQXQBFcTjg90ls5kxQ',
    appId: '1:618037327796:web:6682f1cfdc9e1f5356a4e1',
    messagingSenderId: '618037327796',
    projectId: 'lotayatwodigit',
    authDomain: 'lotayatwodigit.firebaseapp.com',
    storageBucket: 'lotayatwodigit.appspot.com',
    measurementId: 'G-R5EFZ0EG4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB6pDt_J6FjM62JHi9bgIc5sitksYQBCs',
    appId: '1:618037327796:android:eede800d3b04e3ec56a4e1',
    messagingSenderId: '618037327796',
    projectId: 'lotayatwodigit',
    storageBucket: 'lotayatwodigit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8qfG2DOac3FioEy-qOS7wuGsvTHF7G1w',
    appId: '1:618037327796:ios:5d3d5dd54c32226c56a4e1',
    messagingSenderId: '618037327796',
    projectId: 'lotayatwodigit',
    storageBucket: 'lotayatwodigit.appspot.com',
    iosBundleId: 'com.digit.lotaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8qfG2DOac3FioEy-qOS7wuGsvTHF7G1w',
    appId: '1:618037327796:ios:5d3d5dd54c32226c56a4e1',
    messagingSenderId: '618037327796',
    projectId: 'lotayatwodigit',
    storageBucket: 'lotayatwodigit.appspot.com',
    iosBundleId: 'com.digit.lotaya',
  );
}
